<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="35241" started-at="2021-06-02T13:15:40 IST" finished-at="2021-06-02T13:16:16 IST">
    <groups>
      <group name="cucumber">
        <method signature="TestRunnerFile.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.crm.qa.TestRunner.TestRunnerFile@59505b48]" name="feature" class="com.crm.qa.TestRunner.TestRunnerFile"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Test" duration-ms="35241" started-at="2021-06-02T13:15:40 IST" finished-at="2021-06-02T13:16:16 IST">
      <class name="com.crm.qa.TestRunner.TestRunnerFile">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.crm.qa.TestRunner.TestRunnerFile@59505b48]" name="setUpClass" is-config="true" duration-ms="313" started-at="2021-06-02T13:15:40 IST" finished-at="2021-06-02T13:15:41 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.crm.qa.TestRunner.TestRunnerFile@59505b48]" name="feature" duration-ms="34576" started-at="2021-06-02T13:15:41 IST" description="Runs Cucumber Feature" data-provider="features" finished-at="2021-06-02T13:16:15 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[CRM Application Login Test]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO -1 CRM software for customer relationship management, sales, and support.] but found [CRMPRO - CRM software for customer relationship management, sales, and support.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [CRMPRO -1 CRM software for customer relationship management, sales, and support.] but found [CRMPRO - CRM software for customer relationship management, sales, and support.]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at com.crm.qa.TestRunner.TestRunnerFile.feature(TestRunnerFile.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [CRMPRO -1 CRM software for customer relationship management, sales, and support.] but found [CRMPRO - CRM software for customer relationship management, sales, and support.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.crm.qa.StepDefinitions.LoginPageTest.title_of_login_page_is_Free_CRM(LoginPageTest.java:36)
at âœ½.When Title of Login Page is Free CRM(LoginPage.feature:17)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.crm.qa.TestRunner.TestRunnerFile@59505b48]" name="tearDownClass" is-config="true" duration-ms="163" started-at="2021-06-02T13:16:15 IST" finished-at="2021-06-02T13:16:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.crm.qa.TestRunner.TestRunnerFile -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
